17-asp-net-basics/UsersAndAwards/UsersAndAwards/Models/AllAwards.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace Entities
{
    public class AllAwards
    {
        public IEnumerable<Award> awards { get; set; }

        public int id { get; set; }
    }
}

17-asp-net-basics/UsersAndAwards/UsersAndAwards/Models/Award.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace Entities
{
    public class Award
    {
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }

    }
}

17-asp-net-basics/UsersAndAwards/UsersAndAwards/Models/ErrorViewModel.cs
using System;

namespace UsersAndAwards.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

17-asp-net-basics/UsersAndAwards/UsersAndAwards/Models/User.cs
using System;
using System.Collections.Generic;
using System.Text;

namespace Entities
{
    public class User
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime Birthdate { get; set; }
        public int Age { get; set; }

        public List<string> Awards = new List<string>();

        public string Awarding
        {
            get
            {
                string Str = "";
                foreach (var element in Awards)
                { Str += element + " "; }
                return Str;
            }
        }
    }

}

17-asp-net-basics/UsersAndAwards/UsersAndAwards/Controllers/AwardController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BLL;
using Entities;
using Interfaces;

namespace UsersAndAwards.Controllers
{
    public class AwardController : Controller
    {
        private IUserBL _userBll;
        //private IList<Award> _listAward;
        private IAwardBL _awardBL;
        private IEnumerable<Award> _listAward;

        public AwardController(IAwardBL awardBL)
        {
            //_userBll = userBll;
            _awardBL = awardBL;
            _listAward = _awardBL.GetAll();
        }
        public IActionResult Index()
        {
            _listAward = _awardBL.GetAll();
            return View(_listAward);
        }

        [HttpGet]
        public IActionResult AddAward()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddAward(string title, string desc)
        {
            _awardBL.AddAward(title, desc);
            _listAward = _awardBL.GetAll();
            return RedirectToAction("Index");
        }

        public IActionResult DeleteAward(int id)
        {
            var currentAward = new Award();
            foreach (var elem in _listAward)
            {
                if (elem.Id == id)
                {
                    currentAward = elem;
                }
            }
            _awardBL.DeleteAward(currentAward);
            //_listAward.FirstOrDefault(u => u.Id == id);
            _listAward = _awardBL.GetAll();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditAward(int id)
        {
            return View(_listAward.FirstOrDefault(u => u.Id == id));
        }

        [HttpPost]
        public IActionResult EditAward(Award award)
        {
            if(!ModelState.IsValid)
            {
                return View(award);
            }
            //Award award = new Award(ID, title, desc);
            _awardBL.EditAward(award.Id, award.Title, award.Description);
            _listAward = _awardBL.GetAll();
            return RedirectToAction("Index");
        }
    }
}

17-asp-net-basics/UsersAndAwards/UsersAndAwards/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using UsersAndAwards.Models;

namespace UsersAndAwards.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

    }
}

17-asp-net-basics/UsersAndAwards/UsersAndAwards/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BLL;
using Entities;
using Interfaces;


namespace MVC.Controllers
{
    public class UserController : Controller
    {
        private IUserBL _userBll;
        private IAwardBL _awardBL;
        private IEnumerable<User> _listUser;
        private IEnumerable<Award> _listAward;
        private AllAwards allRewards = new AllAwards();

        public UserController(IUserBL userBll, IAwardBL awardBll)
        {
            _userBll = userBll;
            _awardBL = awardBll;
            _listUser = _userBll.GetAll();
            _listAward = _awardBL.GetAll();
            allRewards.awards = _awardBL.GetAll();
        }

        public IActionResult Index()
        {
            _listUser = _userBll.GetAll();
            return View(_listUser);
        }

        [HttpGet]
        public IActionResult AddUser()
        {
            _listAward = _awardBL.GetAll();
            return View(_listAward);
        }

        [HttpPost]
        public IActionResult AddUser(string firstName, string lastName, DateTime birthdate, int age, List<string> awards)
        {
            _userBll.AddUser(firstName, lastName, birthdate, age, awards);
            _listUser = _userBll.GetAll();
            allRewards.awards = _awardBL.GetAll();
            return RedirectToAction("Index");
        }

        public IActionResult DeleteUser(int id)
        {
            var currentUser = new User();
            foreach (var elem in _listUser)
            {
                if (elem.Id == id)
                {
                    currentUser = elem;
                }
            }
            _userBll.DeleteUser(currentUser);
            _listUser = _userBll.GetAll();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditUser(int id)
        {
            _listUser = _userBll.GetAll();
            return View( _listUser.FirstOrDefault(u => u.Id == id));

        }

        [HttpPost]
        public IActionResult EditUser(int ID, string name, string lastName, DateTime birthdate, int age, List<string> awards)
        {
            _userBll.EditUser(ID, name, lastName, birthdate, age, awards);
            _listUser = _userBll.GetAll();
            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult GetAward(int id)
        {
            AllAwards u = new AllAwards();
            u.awards = _awardBL.GetAll();
            u.id = id;
            return View(u);
        }

        [HttpPost]
        public IActionResult GetAward(int id, int award)
        {
            _userBll.GetNewAward(id, award);
            _listUser = _userBll.GetAll();
            return RedirectToAction("Index");
        }

    }
}

17-asp-net-basics/UsersAndAwards/UsersAndAwards/Views/Award/AddAward.cshtml
<html>
<head>

</head>
<body>

    <main>

        <form method="post" class="form-horizontal" role="form">
            <input type="hidden" value="@ViewBag.ID" name="ID" />
            <div class="form-group">
                <label for="title" control-label>Имя:</label>
                <div class="control-label">
                    <input type="text" name="title" class="form-control" required />
                </div>
            </div>

            <div class="form-group">
                <label for="desc">Описание:</label>
                <div class="control-label">
                    <input type="text" name="desc" class="form-control" required />
                </div>
            </div>



            <div class="form-group">
                <div class="form-button">
                    <input type="submit" class="btn-add" value="Добавить" />
                </div>
            </div>
        </form>

    </main>
</body>
</html>

17-asp-net-basics/UsersAndAwards/UsersAndAwards/Views/Award/EditAward.cshtml
@model Entities.Award
@{ var currentaward = Model; }

<html>
<head>

</head>
<body>

    <main>

        <form method="post" class="form-horizontal" role="form">
            <input type="hidden" value="@currentaward.Id" name="Id" />
            <p>Information:</p>
            <div class="form-group">
                <label for="title" class="col-md-2 control-label">Title:</label>
                <div class="col-md-4">
                    <input value="@currentaward.Title" type="text" name="title" class="form-control"/>
                </div>
                <span asp-validation-for="Title"></span>
            </div>

            <div class="form-group">
                <label for="desc" class="col-md-2 control-label">Description:</label>
                <div class="col-md-4">
                    <input type="text" name="description" class="form-control" value="@currentaward.Description" required />
                </div>
            </div>



            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" class="btn btn-default" value="SAVE" />
                </div>
            </div>
        </form>

    </main>
</body>
</html>

17-asp-net-basics/UsersAndAwards/UsersAndAwards/Views/Award/Index.cshtml
@model IEnumerable<Entities.Award>

<html>
<head>
    
</head>
<body>

    <main>
        <table class="table" id="tableAward">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Command</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var award in Model)
                {
                <tr>
                    <td>@award.Title</td>
                    <td>@award.Description</td>
                    <td>
                        @Html.ActionLink("Edit", "EditAward", "Award", new { id = @award.Id }, new { @class = "btn_edit" })
                        @Html.ActionLink("Delete", "DeleteAward", "Award", new { id = @award.Id }, new { @class = "btn_delete" })
                    </td>
                </tr>
                }
            </tbody>
        </table>

    </main>
</body>
</html>

17-asp-net-basics/UsersAndAwards/UsersAndAwards/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

17-asp-net-basics/UsersAndAwards/UsersAndAwards/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UsersAndAwards</title>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="header">
        <div><img id="logo" src="./img/sharingan.jpg"></div>
        <div class="saytName"><a>Оригинальное название сайта</a></div>
    </div>

    <nav>
        <ul id="main_menu">
            <li><a asp-area="" asp-controller="User" asp-action="Index">Пользователи</a></li>
            <li><a asp-area="" asp-controller="Award" asp-action="Index">Награды</a></li>
            <li><a asp-area="" asp-controller="User" asp-action="AddUser">Добавить человека</a></li>
            <li><a asp-area="" asp-controller="Award" asp-action="AddAward">Добавить награду</a></li>
        </ul>
    </nav>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

17-asp-net-basics/UsersAndAwards/UsersAndAwards/Views/User/AddUser.cshtml
<html>
<head>

</head>
<body>
    <div class="main">

        <form method="post" class="form-horizontal" role="form">
            <input type="hidden" value="@ViewBag.ID" name="ID" />
            <div class="form-group">
                <label for="firstName">Имя:</label>
                <div class="control-label">
                    <input type="text" name="firstName" class="form-control" required />
                </div>
            </div>

            <div class="form-group">
                <label for="lastName">Фамилия:</label>
                <div class="control-label">
                    <input type="text" name="lastName" class="form-control" required />
                </div>
            </div>

            <div class="form-group">
                <label for="birthdate">Дата рождения:</label>
                <div class="control-label">
                    <input type="datetime-local" name="birthdate" class="form-control" required />
                </div>
            </div>

            @foreach (var elem in Model)
            {
                <div class="form-group">
                    <div class="radio-group">
                        <div class="award">
                            <label for="radio-button1">@elem.Title</label>
                            <input type="checkbox" name="Awards" class="radio-button" value=@elem.Title />
                        </div>
                    </div>
                </div>
            }

            <div class="form-group">
                <div class="form-button">
                    <input type="submit" class="btn-add" value="Добавить" />
                </div>
            </div>

        </form>

    </div>
</body>
</html>

17-asp-net-basics/UsersAndAwards/UsersAndAwards/Views/User/EditUser.cshtml
@model Entities.User
@{ var currentUser = Model; }

<html>
<head>

</head>
<body>

    <div class="main">

        <form method="post" class="form-horizontal" role="form">
            <input type="hidden" value="@currentUser.Id" name="Id" />
            <div class="form-group">
                <label for="name">Имя:</label>
                <div class="control-label">
                    <input value="@currentUser.FirstName" type="text" name="name" class="form-control" required />
                </div>
            </div>

            <div class="form-group">
                <label for="lastName">Фамилия:</label>
                <div class="control-label">
                    <input type="text" name="lastName" class="form-control" value="@currentUser.LastName" required />
                </div>
            </div>

            <div class="form-group">
                <label for="birthdate">Дата рождения:</label>
                <div class="control-label">
                    <input type="date" name="birthdate" class="form-control" value="@currentUser.Birthdate.ToString("yyyy-MM-dd")" required />
                </div>
            </div>

            @foreach (var elem in currentUser.Awards)
            {
                <div class="form-group">
                    <div class="radio-group">
                        <div class="award">
                            <label for="radio-button1">"@elem"</label>
                            <input type="checkbox" name="Awards" class="radio-button1" value=@elem checked />
                        </div>
                    </div>
                </div>
            }



            <div class="form-group">
                <div class="form-button">
                    <input type="submit" class="btn-add" value="Сохранить" />
                </div>
            </div>
        </form>

    </div>
</body>
</html>

17-asp-net-basics/UsersAndAwards/UsersAndAwards/Views/User/Index.cshtml
<html>
<head>

</head>
<body>

    <main>
        <table class="table" id="tableUser">
            <thead>
                <tr>
                    <th>Фамилия</th>
                    <th>Имя</th>
                    <th>Дата рождения</th>
                    <th>Возраст</th>
                    <th>Награды</th>
                    <th>Команды</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var user in Model)
                {
                    <tr>
                        <td>@user.FirstName</td>
                        <td>@user.LastName</td>
                        <td>@user.Birthdate</td>
                        <td>@user.Age</td>
                        <td>
                            <ul id="awards">
                                @foreach (var item in user.Awards)
                                {
                                    <li>@item</li>
                                }
                            </ul>
                        </td>
                        <td>
                            @Html.ActionLink("изменить", "EditUser", "User", new { id = @user.Id }, new { @class = "btn_edit" })
                            @Html.ActionLink("удалить", "DeleteUser", "User", new { id = @user.Id }, new { @class = "btn_delete" })
                            @Html.ActionLink("добавить награду", "GetAward", "User", new { id = @user.Id }, new { @class = "btn_edit" })
                        </td>
                    </tr>
                }

                </tbody>
        </table>

    </main>
</body>
</html>